# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-16 19:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='children/')),
                ('gender', models.CharField(choices=[('F', 'девочка'), ('M', 'мальчик')], max_length=1, null=True)),
                ('birth_date', models.DateField()),
                ('form', models.SmallIntegerField(null=True)),
                ('group', models.CharField(max_length=1, null=True)),
                ('is_studying', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trustee_name', models.CharField(max_length=200)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stafory.Child')),
            ],
        ),
    ]
